# Generated by Django 2.2.3 on 2019-07-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='comission_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comission_plan', to='comission.ComissionPlan', verbose_name='Comissao'),
        ),
    ]
