# Generated by Django 2.2.3 on 2019-07-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome Comissao')),
                ('porcentagem_menor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem Menor')),
                ('porcentagem_maior', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem Maior')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Minimo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissao_vendedor', to='vendedor.Vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['nome', 'porcentagem_maior', 'porcentagem_menor', 'valor_minimo'],
            },
        ),
    ]
