# Generated by Django 2.2.3 on 2019-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0002_remove_comissao_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Minimo'),
        ),
    ]
