# Generated by Django 2.2.3 on 2019-07-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='endereco',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='vendedor.Endereco', verbose_name='Endereco'),
            preserve_default=False,
        ),
    ]
