# Generated by Django 2.2.3 on 2019-07-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0002_remove_comissao_vendedor'),
        ('vendedor', '0002_auto_20190708_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['nome', 'idade'], 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='plano_comissoes',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='comissao',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comissao', to='comissao.Comissao', verbose_name='Comissao'),
            preserve_default=False,
        ),
    ]
