# Generated by Django 2.2.3 on 2019-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComissionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem Menor')),
                ('upper_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem Maior')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Minimo')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['upper_percentage', 'lower_percentage', 'min_value'],
            },
        ),
    ]
