# Generated by Django 2.2.3 on 2019-07-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0002_auto_20190723_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de venda')),
                ('average_sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Média de vendas')),
                ('notification_date', models.DateTimeField(verbose_name='Data de notificação')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.Seller', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-seller', '-notification_date'],
            },
        ),
    ]
